#!/bin/bash

# Add the flathub.org repositoriy

flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install my apps

flatpak install --user flathub -y \
com.github.Eloston.UngoogledChromium \
com.bitwarden.desktop \
com.github.tchx84.Flatseal \
com.mattjakeman.ExtensionManager \
org.gnome.Calculator \
org.gnome.TextEditor \
org.gnome.eog \
org.gnome.Totem

echo "Done! You should probably reboot so everything is in the right place."
