#!/bin/bash

# Add the flathub.org repo

flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install my apps

flatpak install --user flathub -y		\
	com.belmoussaoui.Obfuscate		\
	com.bitstower.Markets			\
	com.github.bleakgrey.tootle		\
	com.github.fabiocolacio.marker		\
	com.github.gi_lom.dialect		\
	com.github.maoschanz.drawing		\
	com.github.tchx84.Flatseal		\
	com.github.unrud.VideoDownloader	\
	com.uploadedlobster.peek		\
	de.gunibert.Hackgregator		\
	de.haeckerfelix.Fragments		\
	de.haeckerfelix.Shortwave		\
	dev.tchx84.Portfolio			\
	fr.romainvigier.MetadataCleaner		\
	io.github.seadve.Kooha			\
	org.gabmus.whatip			\
	org.gnome.Calculator			\
	org.gnome.Clocks			\
	org.gnome.eog				\
	org.gnome.Epiphany			\
	org.gnome.Fractal			\
	org.gnome.Geary				\
	org.gnome.gedit				\
	org.gnome.Maps				\
	org.gnome.Screenshot			\
	org.gnome.SoundRecorder			\
	org.gnome.Totem				\
	org.gnome.Weather

echo "Done! You should probably reboot so everything is in the right place."
