#!/bin/bash

_please-root ()
{
	if [ "$EUID" -ne 0 ]
		then echo "Please run this command as root"
		exit
	fi
}

_grub ()
{
	_please-root
	apt install -y imagemagick
	convert -size 1920x1080 xc:black bg.png
	cp bg.png /boot/grub/
	rm bg.png
	sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/g' /etc/default/grub
	sed -i 's/#GRUB_GFXMODE=640x480/GRUB_GFXMODE=1920x1080/g' /etc/default/grub
	update-grub
}

_aliases ()
{
	echo "alias i='sudo apt install -y'" >> /home/arteeh/.bashrc
	echo "alias r='sudo apt purge -y'" >> /home/arteeh/.bashrc
	echo "alias l='clear;apt list --installed'" >> /home/arteeh/.bashrc
	echo "" >> /home/arteeh/.bashrc
	echo "alias u='sudo apt update'" >> /home/arteeh/.bashrc
	echo "alias d='sudo apt dist-upgrade -y'" >> /home/arteeh/.bashrc
	echo "alias a='sudo apt autoremove --purge -y'" >> /home/arteeh/.bashrc
	echo "alias c='sudo apt clean'" >> /home/arteeh/.bashrc
	echo "alias udac='u;d;a;c'" >> /home/arteeh/.bashrc
	echo "" >> /home/arteeh/.bashrc
	echo "alias fu='flatpak update -y'" >> /home/arteeh/.bashrc
	echo "alias fi='flatpak --user install -y'"  >> /home/arteeh/.bashrc
	echo "alias fr='flatpak remove -y --delete-data'"  >> /home/arteeh/.bashrc
	echo "alias fa='flatpak remove -y --unused --delete-data'"  >> /home/arteeh/.bashrc
	echo "alias fl='flatpak list'"  >> /home/arteeh/.bashrc
	echo "alias fufa='fu;fa'"  >> /home/arteeh/.bashrc
	echo "" >> /home/arteeh/.bashrc
	echo "alias up='udac;fufa'" >> /home/arteeh/.bashrc
	echo "" >> /home/arteeh/.bashrc
	echo "alias gs='git status'" >> /home/arteeh/.bashrc
	echo "alias ga='git add'" >> /home/arteeh/.bashrc
	echo "alias gc='git commit'" >> /home/arteeh/.bashrc
	echo "alias gp='git push'" >> /home/arteeh/.bashrc
	echo "alias g='ga .;gc;gp'" >> /home/arteeh/.bashrc
}

_debian-upgrade ()
{
	_please-root
	echo "deb http://deb.debian.org/debian testing main contrib non-free" > /etc/apt/sources.list
	apt update
	apt dist-upgrade -y
	apt autoremove --purge -y
	apt clean
}

_debian-drivers ()
{
	_please-root
	apt install -y firmware-linux
	read -p 'Desktop or laptop? d/l: ' device
	if [ device == "d" ] ; then
		apt install -y firmware-realtek
	elif [ device == "l" ] ; then
		apt install -y firmware-iwlwifi
	fi
}

_debian-gnome ()
{
	_please-root
	
	apt install -y \
		plymouth \
		plymouth-themes \
		gnome-core \
		fonts-noto \
		gedit-plugin-color-picker \
		gedit-plugin-text-size \
		flatpak
	
	plymouth-set-default-theme -R spinner
	
	apt purge -y \
		imagemagick \
		termit \
		popularity-contest \
		vim-common \
		vim-tiny \
		needrestart \
		malcontent \
		firefox-esr \
		yelp \
		im-config \
		eog \
		baobab \
		evince \
		totem \
		gnome-calculator \
		gnome-characters \
		gnome-contacts \
		gnome-disk-utility \
		gnome-font-viewer \
		gnome-logs \
		gnome-shell-extension* \
		gnome-software \
		gnome-sushi \
		gnome-system-monitor \
		gnome-tweaks \
		system-config-printer
	
	apt autoremove --purge -y
	
	# Add the empty file template
	touch '/home/arteeh/Templates/Empty file'
	chown arteeh '/home/arteeh/Templates/Empty file'
	chmod +rw '/home/arteeh/Templates/Empty file'
}

_fix-network ()
{
	# Disable built in network so networkmanager can take control
	nano /etc/network/interfaces
	sed -i 's/allow-hotplug/#allow-hotplug/g' /etc/network/interfaces
	sed -i 's/iface enp1s0 inet dhcp/#iface enp1s0 inet dhcp/g' /etc/network/interfaces
}

_flatpak ()
{
	# Set up flathub
	flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

	# Get apps
	flatpak install --user flathub -y \
		org.gnome.eog \
		org.gnome.Boxes \
		org.gnome.Epiphany \
		org.gnome.Extensions \
		org.gnome.Totem \
		org.gnome.Geary \
		org.gnome.Calculator \
		org.gnome.Clocks \
		org.gnome.Fractal \
		org.gnome.Characters \
		com.uploadedlobster.peek \
		com.transmissionbt.Transmission \
		org.glimpse_editor.Glimpse \
		com.spotify.Client \
		com.discordapp.Discord \
		com.microsoft.Teams
}

_debian ()
{
	_grub
	_aliases
	_debian-upgrade
	_debian-drivers
	_debian-gnome
	_fix-network
}

_arch ()
{
	echo "Nope!"
}

_help ()
{
	echo "./linux debian	-	Set up a Debian netinstall"
	echo "./linux arch	-	Set up an Anarchy minimal install"
	echo "./linux flatpak	-	Configure flathub and install my apps"
}

if [ "$1" == "debian" ]
then
	_debian
elif [ "$1" == "arch" ]
then
	_arch
elif [ "$1" == "flatpak" ]
then
	_flatpak
else
	_help
fi

