#!/bin/bash

_please-root ()
{
	if [ "$EUID" -ne 0 ]
		then echo "Please run this command as root"
		exit
	fi
}

_install ()
{
	os=$(hostnamectl | grep "Operating System")
	
	if [ os == *"Debian"* ] ; then
		apt install -y $1
	elif [ os == *"Arch"* ] ; then
		pacman -Syu --noconfirm $1
	fi
}

_remove ()
{
	os=$(hostnamectl | grep "Operating System")
	
	if [ os == *"Debian"* ]
		apt purge -y $1
	elif [ os == *"Arch"* ]
		pacman -Rsc --noconfirm $1
	fi
}

_grub ()
{
	echo "Setting up grub..."
	
	_install imagemagick
	convert -size 1920x1080 xc:black bg.png
	_remove imagemagick
	
	cp bg.png /boot/grub/
	rm bg.png
	
	sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/g' /etc/default/grub
	sed -i 's/#GRUB_GFXMODE=640x480/GRUB_GFXMODE=1920x1080/g' /etc/default/grub
	
	update-grub
	
	echo "Done setting up grub"
}

_aliases ()
{
	echo "Adding general aliases..."
	
	# Flatpak
	echo "alias fu='flatpak update -y'" >> /home/arteeh/.bashrc
	echo "alias fi='flatpak --user install -y'"  >> /home/arteeh/.bashrc
	echo "alias fr='flatpak remove -y --delete-data'"  >> /home/arteeh/.bashrc
	echo "alias fa='flatpak remove -y --unused --delete-data'"  >> /home/arteeh/.bashrc
	echo "alias fl='flatpak list'"  >> /home/arteeh/.bashrc
	
	# Git
	echo "alias gs='git status'" >> /home/arteeh/.bashrc
	echo "alias ga='git add'" >> /home/arteeh/.bashrc
	echo "alias gc='git commit'" >> /home/arteeh/.bashrc
	echo "alias gp='git push'" >> /home/arteeh/.bashrc
	echo "alias g='ga .;gc;gp'" >> /home/arteeh/.bashrc
	
	echo "Done adding general aliases"
}

_debian-aliases ()
{
	echo "Adding Debian-specific aliases..."
	
	# Apt
	echo "alias i='sudo apt install -y'" >> /home/arteeh/.bashrc
	echo "alias r='sudo apt purge -y'" >> /home/arteeh/.bashrc
	echo "alias l='clear;apt list --installed'" >> /home/arteeh/.bashrc
	echo "alias u='sudo apt update'" >> /home/arteeh/.bashrc
	echo "alias d='sudo apt dist-upgrade -y'" >> /home/arteeh/.bashrc
	echo "alias a='sudo apt autoremove --purge -y'" >> /home/arteeh/.bashrc
	echo "alias c='sudo apt clean'" >> /home/arteeh/.bashrc
	
	# Update everything
	echo "alias up='u;d;a;c;fu;fa'" >> /home/arteeh/.bashrc
	
	echo "Done adding Debian-specific aliases"
}

_arch-aliases ()
{
	echo "Adding Arch-specific aliases..."
	
	# Pacman
	echo "alias i='sudo pacman -Syu --noconfirm'" >> /home/arteeh/.bashrc
	echo "alias r='sudo pacman -Rsc --noconfirm'" >> /home/arteeh/.bashrc
	echo "alias l='pacman -Qs'" >> /home/arteeh/.bashrc
	echo "alias u='sudo pacman -Syu --noconfirm'" >> /home/arteeh/.bashrc
	echo "alias a='sudo pacman -Rns $(pacman -Qdtq)'" >> /home/arteeh/.bashrc
	
	# Update everything
	echo "alias up='u;a;fu;fa'" >> /home/arteeh/.bashrc
	
	echo "Done adding Arch-specific aliases"
}

_debian-upgrade ()
{
	echo "Upgrading Debian to testing..."
	
	echo "deb http://deb.debian.org/debian testing main contrib non-free" > /etc/apt/sources.list
	
	apt update
	apt dist-upgrade -y
	apt autoremove --purge -y
	apt clean
	
	echo "Done upgrading Debian to testing"
}

_debian-packages ()
{
	echo "Installing packages for Debian..."
	
	read -p 'Desktop or laptop? d/l: ' device
	if [ device == "d" ] ; then
		apt install -y firmware-realtek
	elif [ device == "l" ] ; then
		apt install -y firmware-iwlwifi
	fi
	
	apt install -y \
		firmware-linux \
		plymouth \
		plymouth-themes \
		gnome-core \
		fonts-noto \
		gedit-plugin-color-picker \
		gedit-plugin-text-size \
		flatpak
	
	plymouth-set-default-theme -R spinner
	
	apt purge -y \
		imagemagick \
		termit \
		popularity-contest \
		vim-common \
		vim-tiny \
		needrestart \
		malcontent \
		firefox-esr \
		yelp \
		im-config \
		eog \
		baobab \
		evince \
		totem \
		gnome-calculator \
		gnome-characters \
		gnome-contacts \
		gnome-disk-utility \
		gnome-font-viewer \
		gnome-logs \
		gnome-shell-extension* \
		gnome-software \
		gnome-sushi \
		gnome-system-monitor \
		gnome-tweaks \
		system-config-printer
	
	apt autoremove --purge -y
	
	echo "Done installing packages for Debian"
}

_arch-packages ()
{
	echo "Installing packages for Arch..."
	
	pacman -Syu --no-confirm \
		plymouth
		gnome-shell \
		gdm \
		gedit \
		gedit-plugins \
		nautilus \
		gnome-terminal \
		gnome-control-center \
		gnome-tweaks \
		gnome-screenshot \
		noto-fonts \
		noto-fonts-cjk \
		noto-fonts-emoji \
		noto-fonts-extra \
		flatpak
	
	#TODO Set up plymouth (https://wiki.archlinux.org/index.php/Plymouth)
	
	pacman -Rsc --no-confirm \
		vim
	
	echo "Done installing packages for Arch"
}

_templates ()
{
	echo "Setting up templates..."
	
	# Add the empty file template
	touch '/home/arteeh/Templates/Empty file'
	chown arteeh '/home/arteeh/Templates/Empty file'
	chmod +rw '/home/arteeh/Templates/Empty file'
	
	echo "Done setting up templates"
}

_fix-network ()
{
	echo "Disabling the built-in network for networkmanager..."
	
	# Disable built in network so networkmanager can take control
	nano /etc/network/interfaces
	sed -i 's/allow-hotplug/#allow-hotplug/g' /etc/network/interfaces
	sed -i 's/iface enp1s0 inet dhcp/#iface enp1s0 inet dhcp/g' /etc/network/interfaces
	
	echo "Done disabling the built-in network for networkmanager"
}

_flatpak ()
{
	echo "Adding the flathub repo..."
	
	# Set up flathub
	flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	
	echo "Done adding the flathub repo"
	
	echo "Installing apps..."
	
	# Get apps
	flatpak install --user flathub -y \
		org.gnome.eog \
		org.gnome.Boxes \
		org.gnome.Epiphany \
		org.gnome.Extensions \
		org.gnome.Totem \
		org.gnome.Geary \
		org.gnome.Calculator \
		org.gnome.Clocks \
		org.gnome.Fractal \
		org.gnome.Characters \
		com.uploadedlobster.peek \
		com.transmissionbt.Transmission \
		org.glimpse_editor.Glimpse \
		com.spotify.Client \
		com.discordapp.Discord \
		com.microsoft.Teams
	
	echo "Done installing apps"
}

_debian ()
{
	echo "Setting up Debian..."
	
	_grub
	_aliases
	_debian-aliases
	_debian-upgrade
	_debian-packages
	_templates
	_fix-network
	
	echo "All done!"
}

_arch ()
{
	echo "Setting up Arch..."
	
	_grub
	_aliases
	_arch-aliases
	_arch-packages
	_templates
	
	echo "All done!"
}

_help ()
{
	echo "./linux debian	-	Set up a Debian netinstall"
	echo "./linux arch	-	Set up an Anarchy minimal install"
	echo "./linux flatpak	-	Configure flathub and install my apps"
}

# parameters, most are just there for testing
if [ "$1" == "debian" ]
then
	_debian
elif [ "$1" == "arch" ]
then
	_arch
elif [ "$1" == "flatpak" ]
then
	_flatpak
elif [ "$1" == "grub" ]
then
	_grub
elif [ "$1" == "aliases" ]
then
	_aliases
elif [ "$1" == "debian-aliases" ]
then
	_debian-aliases
elif [ "$1" == "arch-aliases" ]
then
	_arch-aliases
elif [ "$1" == "debian-upgrade" ]
then
	_debian-upgrade
elif [ "$1" == "debian-packages" ]
then
	_debian-packages
elif [ "$1" == "arch-packages" ]
then
	_arch-packages
elif [ "$1" == "templates" ]
then
	_templates
elif [ "$1" == "fix-network" ]
then
	_fix-network
else
	_help
fi

