#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Aliases

# Apt
echo "alias i='sudo apt install -y'" >> /home/mobian/.bashrc
echo "alias r='sudo apt purge -y'" >> /home/mobian/.bashrc
echo "alias l='clear;apt list --installed'" >> /home/mobian/.bashrc
echo "alias u='sudo apt update'" >> /home/mobian/.bashrc
echo "alias d='sudo apt dist-upgrade -y'" >> /home/mobian/.bashrc
echo "alias a='sudo apt autoremove --purge -y'" >> /home/mobian/.bashrc
echo "alias c='sudo apt clean'" >> /home/mobian/.bashrc

# Flatpak
echo "alias fu='flatpak update -y'" >> /home/mobian/.bashrc
echo "alias fi='flatpak --user install -y'"  >> /home/mobian/.bashrc
echo "alias fr='flatpak remove -y --delete-data'"  >> /home/mobian/.bashrc
echo "alias fa='flatpak remove -y --unused --delete-data'"  >> /home/mobian/.bashrc
echo "alias fl='flatpak list'"  >> /home/mobian/.bashrc

# Git
echo "alias gs='git status'" >> /home/mobian/.bashrc
echo "alias ga='git add'" >> /home/mobian/.bashrc
echo "alias gc='git commit'" >> /home/mobian/.bashrc
echo "alias gp='git push'" >> /home/mobian/.bashrc
echo "alias g='ga .;gc;gp'" >> /home/mobian/.bashrc

# Update everything
echo "alias up='u;d;a;c;fu;fa'" >> /home/mobian/.bashrc

# Upgrade to unstable

echo "deb http://deb.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list
echo "deb http://repo.mobian-project.org/ unstable main contrib non-free" > /etc/apt/sources.list.d/mobian.list
apt update
apt dist-upgrade -y
apt autoremove --purge -y
apt clean

# Remove packages

apt purge -y \
	baobab \
	chatty \
	eog \
	epiphany-browser \
	evince \
	file-roller \
	firefox-esr* \
	fractal \
	fwupd \
	geary \
	gedit \
	gnome-2048 \
	gnome-authenticator \
	gnome-calculator \
	gnome-calendar \
	gnome-calls \
	gnome-characters \
	gnome-chess \
	gnome-clocks \
	gnome-contacts \
	gnome-disk-utility \
	gnome-font-viewer \
	gnome-initial-setup \
	gnome-logs \
	gnome-maps \
	gnome-shell-extension* \
	gnome-software \
	gnome-sound-recorder \
	gnome-sushi \
	gnome-system-monitor \
	gnome-todo \
	gnome-tweaks \
	gnome-usage \
	gnome-weather \
	imagemagick \
	im-config \
	im-config \
	lollypop
	malcontent \
	needrestart \
	nemo \
	popularity-contest \
	portfolio-filemanager \
	powersupply \
	system-config-printer \
	telegram* \
	termit \
	totem \
	vim* \
	webext* \
	yelp \
	youtube-dl

sudo rm /usr/share/applications/nm-connection-editor.desktop

apt install -y				\
	flatpak				\
	mutter				\
	gdm3				\
	gnome-shell			\
	gnome-control-center

apt autoremove --purge -y

echo "Done! You should probably reboot so everything is in the right place."

