#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Remove packages

apk del --purge \
	calls \
	chatty \
	eog \
	firefox-esr \
	gedit \
	gnome-calculator \
	gnome-clocks \
	gnome-contacts \
	gnome-software \
	megapixels \
	mobile-config-firefox \
	portfolio \
	postmarketos-welcome-gtk3

apk del --purge

apk add flatpak

echo "Done! You should probably reboot so everything is in the right place."
