#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Aliases

# Flatpak
echo "alias u='flatpak update -y'" >> /home/arteeh/.bashrc
echo "alias i='flatpak --user install -y'"  >> /home/arteeh/.bashrc
echo "alias r='flatpak remove -y --delete-data'"  >> /home/arteeh/.bashrc
echo "alias a='flatpak remove -y --unused --delete-data'"  >> /home/arteeh/.bashrc
echo "alias l='flatpak list'"  >> /home/arteeh/.bashrc

# Git
echo "alias gs='git status'" >> /home/arteeh/.bashrc
echo "alias ga='git add'" >> /home/arteeh/.bashrc
echo "alias gc='git commit'" >> /home/arteeh/.bashrc
echo "alias gp='git push'" >> /home/arteeh/.bashrc
echo "alias g='ga .;gc;gp'" >> /home/arteeh/.bashrc

# Enable automatic updates

sed -i 's/#AutomaticUpdatePolicy=check/AutomaticUpdatePolicy=stage/g' /etc/rpm-ostreed.conf
rpm-ostree reload
systemctl enable rpm-ostreed-automatic.timer --now

# Remove default apps installed to system

rpm-ostree override remove firefox firefox-langpacks gnome-tour gnome-software gnome-software-rpm-ostree yelp 

flatpak remove -y --delete-data \
org.fedoraproject.MediaWriter \
org.fedoraproject.Platform \
org.gnome.Calculator \
org.gnome.Calendar \
org.gnome.Characters \
org.gnome.Connections \
org.gnome.Contacts \
org.gnome.Evince \
org.gnome.Extensions \
org.gnome.Logs \
org.gnome.Maps \
org.gnome.NautilusPreviewer \
org.gnome.TextEditor \
org.gnome.Weather \
org.gnome.baobab \
org.gnome.clocks \
org.gnome.eog \
org.gnome.font-viewer

flatpak remove -y --unused --delete-data

flatpak remote-delete fedora
flatpak remote-delete flathub

echo "Done! You should probably reboot so everything is in the right place."
