#!/bin/bash

# Remove default apps installed as root

flatpak remove -y --delete-data \
org.fedoraproject.MediaWriter \
org.fedoraproject.Platform \
org.gnome.Calculator \
org.gnome.Calendar \
org.gnome.Characters \
org.gnome.Connections \
org.gnome.Contacts \
org.gnome.Evince \
org.gnome.Extensions \
org.gnome.Logs \
org.gnome.Maps \
org.gnome.NautilusPreviewer \
org.gnome.TextEditor \
org.gnome.Weather \
org.gnome.baobab \
org.gnome.clocks \
org.gnome.eog \
org.gnome.font-viewer

flatpak remove -y --unused --delete-data

flatpak remote-delete fedora
flatpak remote-delete flathub

# Add the flathub.org repository as user

flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install my apps

flatpak install --user flathub -y \
com.github.Eloston.UngoogledChromium \
com.bitwarden.desktop \
com.github.tchx84.Flatseal \
com.mattjakeman.ExtensionManager \
org.gnome.Calculator \
org.gnome.TextEditor \
org.gnome.eog \
org.gnome.Totem

# Add chromium tweaks

cp ./chromium-flags.conf ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf

# Fix the chromium tiny cursor issue

mkdir ~/.icons && cp -r /usr/share/icons/Adwaita ~/.icons/default
