#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Remove default apps and repos installed as root

flatpak remove -y --delete-data \
org.fedoraproject.MediaWriter \
org.fedoraproject.Platform \
org.gnome.Calculator \
org.gnome.Calendar \
org.gnome.Characters \
org.gnome.Connections \
org.gnome.Contacts \
org.gnome.Evince \
org.gnome.Extensions \
org.gnome.Logs \
org.gnome.Maps \
org.gnome.NautilusPreviewer \
org.gnome.TextEditor \
org.gnome.Weather \
org.gnome.baobab \
org.gnome.clocks \
org.gnome.eog \
org.gnome.font-viewer

flatpak remove -y --unused --delete-data

flatpak remote-delete fedora
flatpak remote-delete flathub
