#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Set up grub

apt install -y imagemagick --no-install-recommends
convert -size 1920x1080 xc:black bg.png
cp bg.png /boot/grub/
rm bg.png
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/g' /etc/default/grub
sed -i 's/#GRUB_GFXMODE=640x480/GRUB_GFXMODE=1920x1080/g' /etc/default/grub
update-grub

# Aliases

# Apt
echo "alias i='sudo apt install -y'" >> /home/arteeh/.bashrc
echo "alias r='sudo apt purge -y'" >> /home/arteeh/.bashrc
echo "alias l='clear;apt list --installed'" >> /home/arteeh/.bashrc
echo "alias u='sudo apt update'" >> /home/arteeh/.bashrc
echo "alias d='sudo apt dist-upgrade -y'" >> /home/arteeh/.bashrc
echo "alias a='sudo apt autoremove --purge -y'" >> /home/arteeh/.bashrc
echo "alias c='sudo apt clean'" >> /home/arteeh/.bashrc
# Flatpak
echo "alias fu='flatpak update -y'" >> /home/arteeh/.bashrc
echo "alias fi='flatpak --user install -y'"  >> /home/arteeh/.bashrc
echo "alias fr='flatpak remove -y --delete-data'"  >> /home/arteeh/.bashrc
echo "alias fa='flatpak remove -y --unused --delete-data'"  >> /home/arteeh/.bashrc
echo "alias fl='flatpak list'"  >> /home/arteeh/.bashrc
# Git
echo "alias gs='git status'" >> /home/arteeh/.bashrc
echo "alias ga='git add'" >> /home/arteeh/.bashrc
echo "alias gc='git commit'" >> /home/arteeh/.bashrc
echo "alias gp='git push'" >> /home/arteeh/.bashrc
echo "alias g='ga .;gc;gp'" >> /home/arteeh/.bashrc
# Update everything
echo "alias up='u;d;a;c;fu;fa'" >> /home/arteeh/.bashrc

# Upgrade to unstable

echo "deb http://deb.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list
apt update
apt dist-upgrade -y
apt autoremove --purge -y
apt clean

# Install packages

apt install -y \
	firmware-linux \
	firmware-realtek \
	firmware-iwlwifi \
	plymouth \
	plymouth-themes \
	gnome-core \
	fonts-noto \
	flatpak

plymouth-set-default-theme -R spinner

apt purge -y \
	imagemagick \
	termit \
	popularity-contest \
	vim-common \
	vim-tiny \
	needrestart \
	malcontent \
	firefox-esr \
	yelp \
	im-config \
	eog \
	baobab \
	evince \
	totem \
	gedit \
	gnome-calculator \
	gnome-characters \
	gnome-contacts \
	gnome-disk-utility \
	gnome-font-viewer \
	gnome-logs \
	gnome-shell-extension* \
	gnome-software \
	gnome-sushi \
	gnome-system-monitor \
	gnome-tweaks \
	system-config-printer

apt autoremove --purge -y

# Add the empty file template
touch '/home/arteeh/Templates/Empty file'
chown arteeh '/home/arteeh/Templates/Empty file'
chmod +rw '/home/arteeh/Templates/Empty file'

# Disable built in network so networkmanager can take control
sed -i 's/allow-hotplug/#allow-hotplug/g' /etc/network/interfaces
sed -i 's/iface enp1s0 inet dhcp/#iface enp1s0 inet dhcp/g' /etc/network/interfaces
#nano /etc/network/interfaces

# Remove the network manager "app"
rm /usr/share/applications/nm-connection-editor.desktop

echo "Done! You should probably reboot so everything is in the right place."
