#!/bin/bash

# Root check
if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Set hostname
hostnamectl set-hostname rock

# Add docker repo
curl https://download.docker.com/linux/fedora/docker-ce.repo -O /etc/yum.repos.d/docker-ce.repo

# Install packages
rpm-ostree install	\
	docker-ce	\
	docker-compose

# Configure the firewall
firewall-cmd --add-service=http --permanent
firewall-cmd --add-service=https --permanent
firewall-cmd --add-service=ssh --permanent
firewall-cmd --add-port=81/tcp --permanent
