#!/bin/bash

# Root check

if [ "$EUID" -ne 0 ]
	then echo "Please run this command as root"
	exit
fi

# Aliases

# Apt
echo "alias i='sudo apt install -y'" >> /home/arteeh/.bashrc
echo "alias r='sudo apt purge -y'" >> /home/arteeh/.bashrc
echo "alias l='clear;apt list --installed'" >> /home/arteeh/.bashrc
echo "alias u='sudo apt update'" >> /home/arteeh/.bashrc
echo "alias d='sudo apt dist-upgrade -y'" >> /home/arteeh/.bashrc
echo "alias a='sudo apt autoremove --purge -y'" >> /home/arteeh/.bashrc
echo "alias c='sudo apt clean'" >> /home/arteeh/.bashrc
# Flatpak
echo "alias fu='flatpak update -y'" >> /home/arteeh/.bashrc
echo "alias fi='flatpak --user install -y'"  >> /home/arteeh/.bashrc
echo "alias fr='flatpak remove -y --delete-data'"  >> /home/arteeh/.bashrc
echo "alias fa='flatpak remove -y --unused --delete-data'"  >> /home/arteeh/.bashrc
echo "alias fl='flatpak list'"  >> /home/arteeh/.bashrc
# Git
echo "alias gs='git status'" >> /home/arteeh/.bashrc
echo "alias ga='git add'" >> /home/arteeh/.bashrc
echo "alias gc='git commit'" >> /home/arteeh/.bashrc
echo "alias gp='git push'" >> /home/arteeh/.bashrc
echo "alias g='ga .;gc;gp'" >> /home/arteeh/.bashrc
# Update everything
echo "alias up='u;d;a;c;fu;fa'" >> /home/arteeh/.bashrc

# Upgrade to testing

echo "deb http://deb.debian.org/debian testing main contrib non-free" > /etc/apt/sources.list
apt update
apt dist-upgrade -y
apt autoremove --purge -y
apt clean

# Remove packages

apt purge -y \
	baobab \
	chatty \
	eog \
	epiphany-browser \
	evince \
	file-roller \
	firefox-esr* \
	flashlight \
	fractal \
	fwupd \
	geary \
	gedit \
	gnome-2048 \
	gnome-authenticator \
	gnome-calculator \
	gnome-calendar \
	gnome-calls \
	gnome-characters \
	gnome-chess \
	gnome-clocks \
	gnome-contacts \
	gnome-disk-utility \
	gnome-font-viewer \
	gnome-initial-setup \
	gnome-logs \
	gnome-maps \
	gnome-shell-extension* \
	gnome-software \
	gnome-sound-recorder \
	gnome-sushi \
	gnome-system-monitor \
	gnome-todo \
	gnome-tweaks \
	gnome-usage \
	gnome-weather \
	im-config \
	imagemagick \
	lollypop \
	malcontent \
	megapixels \
	needrestart \
	nemo \
	popularity-contest \
	portfolio-filemanager \
	powersupply \
	system-config-printer \
	telegram* \
	termit \
	totem \
	vim* \
	webext* \
	yelp \
	youtube-dl

apt autoremove --purge -y

# Remove the network manager "app"
rm /usr/share/applications/nm-connection-editor.desktop

# Add the empty file template
touch '/home/arteeh/Templates/Empty file'
chown arteeh '/home/arteeh/Templates/Empty file'
chmod +rw '/home/arteeh/Templates/Empty file'

echo "Done! You should probably reboot so everything is in the right place."
